# Generated by Django 6.0.1 on 2026-01-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='join_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='start_url',
            field=models.TextField(),
        ),
    ]
